# Generated by Django 5.0.7 on 2024-07-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Terea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(blank=True, max_length=150)),
                (
                    "prioridad",
                    models.CharField(
                        blank=True,
                        choices=[("0", "Baja"), ("1", "Media"), ("2", "Alta")],
                        max_length=1,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "categoria",
                    models.ManyToManyField(
                        related_name="tareas", to="tareas.categoria"
                    ),
                ),
            ],
        ),
    ]
