# Generated by Django 5.0.7 on 2024-07-30 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Terea",
            new_name="Tarea",
        ),
    ]
