# Generated by Django 5.0.7 on 2024-07-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0002_rename_terea_tarea"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarea",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha",
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name="tarea",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tareas",
                to="tareas.categoria",
            ),
        ),
    ]
