# Generated by Django 5.0.7 on 2024-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0003_remove_tarea_categoria_alter_tarea_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="prioridad",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
