# Generated by Django 5.0.7 on 2024-08-03 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0005_alter_tarea_prioridad"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="agregada",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tarea",
            name="prioridad",
            field=models.CharField(
                choices=[("0", "Baja"), ("1", "Media"), ("2", "Alta")],
                default="0",
                max_length=1,
            ),
        ),
    ]
