# Generated by Django 5.0.7 on 2024-08-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0006_tarea_agregada_alter_tarea_prioridad"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="completa",
            field=models.BooleanField(default=False),
        ),
    ]
